name = "LoopPoly"
uuid = "4edc584b-a88b-4acf-80bb-891198a11e01"
authors = ["Yingbo Ma <mayingbo5@gmail.com> and Chris Elrod <elrodc@gmail.com>"]
version = "0.1.0"

[deps]
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
SIMD = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
