name = "SIMDPolynomials"
uuid = "4edc584b-a88b-4acf-80bb-891198a11e01"
authors = ["Yingbo Ma <mayingbo5@gmail.com> and Chris Elrod <elrodc@gmail.com>"]
version = "0.1.0"

[deps]
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
MultivariatePolynomials = "0.5"
MutableArithmetics = "1"
SIMD = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
